### ISSUE TITLE
Meta: Should the question about usage of a feature be more precise?

### ISSUE THREAD

**Issue by SebastianZ** [Devographics/surveys#34]
When I participated in the past surveys, I sometimes didn't know whether to choose "Know about it" or "Have used it".

As a CSSWG member and CSS enthusiast, I almost know all of the CSS features and try them out as soon as they are available. Though many of those things didn't find their way into production code at that point. So it feels a bit weird to say that I used a feature when I was just testing how it works.

So maybe an explanation of the options would already help in that situation.
There might also be three options for "having heard/read about it", "having tried it out" and "using it on a website".

Sebastian

**Comment by SebastianZ** [comment]
This question isn't actually restricted to CSS features but also technologies, tools and environments.

Sebastian

**Comment by LeaVerou** [comment]
Unfortunately, we cannot change the three options, because then we lose the ability to compare their stats over time.
We can definitely clarify what they mean though! 👍🏼 
FWIW trying out how it works in a codepen totally counts as usage! The goal of the survey is not to measure usage % on live websites, there are other methods for that (Web Almanac, Chrome usage metrics etc), it's to measure developer experience.
