### ISSUE TITLE
State of React 2023 Preliminary Discussions

### ISSUE THREAD

**Issue by SachaG** [Devographics/surveys#85]
**EDIT: adding the link to the survey preview:  https://survey.devographics.com/en-US/survey/state-of-react/2023/**

Although it's still early days, we are thinking about holding our first ever "State of React" survey this year, so I'm opening this thread to collect feedback, suggestions, ideas, or anything else you'd like to share about the topic. 

A few questions to get the discussion started: 

- What are your biggest issues or pain points with React today?
- What do you see as major trends in the React ecosystem going forward?
- What questions would you like a React survey to answer?
- Which React libraries or tools are you most excited about today?
- Which React competitors do you think pose the biggest challenge?

**Comment by cassidoo** [comment]
I'd be curious to see thoughts from folks around:

- How they are learning new React techniques/concepts
- Preferences around rendering (CSR, SSR, etc)
- Thoughts around using/integrating frameworks in larger codebases (since that's what the core team is pushing a lot more nowadays)

**Comment by SachaG** [comment]
> * Thoughts around using/integrating frameworks in larger codebases (since that's what the core team is pushing a lot more nowadays)

Do you think you could elaborate on that? Do you mean using React within the context of Next.js, Remix, etc. as opposed to more stand-alone environments like CRA or Vite?

**Comment by markerikson** [comment]
@SachaG loosely put: with the release of the new React docs, and the release of Next 13.4 with React Server Components integration, the React team has very firmly made it clear they want React users to build apps with frameworks that have some kind of routing / data fetching / SSR built in already (Next, Remix, Gatsby, Expo?), and _not_ using pure SPA build setups where you have to add all the pieces yourself (CRA, Vite, your own Webpack config).

This has caused a lot of concern and frustration in the React community, as folks are confused about the benefits or intent, feeling left behind, unsure how to migrate existing pure SPAs, and concerned about non-Node backends being unable to take advantage of RSCs.

As an example, see this recent tweet thread that was based on chatter at Reactathon this last week, starting from these initial tweets (and with a dozen sub threads):

- https://twitter.com/Swizec/status/1653605092371873792
- https://twitter.com/acemarke/status/1653638787661168643

There's a couple dozen different overlapping concerns at this point, and it's pretty hard to sum up or follow the discussions :)

**Comment by SachaG** [comment]
OK, that's what I thought. Yes I think that's probably in the top 3 concerns of the community right now, and the survey should definitely cover that.

**Comment by slorber** [comment]
I am particularly interested to know more about React as a cross-platform solution. 

Who is using which platform/renderer, for how long, and how do platforms "overlap" 
(ie how many React web devs are also experienced React-Native devs, React-Three-Fiber devs and vice versa)

**Comment by SachaG** [comment]
You can preview the survey here: 

https://survey.devographics.com/en-US/survey/state-of-react/2023

And here's a link to the full outline in YAML format: 

https://github.com/Devographics/surveys/blob/main/state_of_react/react2023/questions.yml

You'll see there are some items commented out in the YAML when I decided to leave them out, mainly because they felt too niche or else were deprecated. But I'm happy to discuss!

This is just the first version so please take it more as a starting point than a finished product. Feedback welcome!

**Comment by markerikson** [comment]
Thoughts / suggestions:

- Ask what version of React they're currently on? (16, 17, 18)
- Would like to see RTK Query added to the "Data Fetching" list
- Might be nice to add a "just React state" option to the "State Management" section
- Wish there was some way to differentiate between legacy "hand-written" Redux and modern Redux Toolkit
- Add React Final Form to "Forms"
- Add some form of "Effects" or "Dependencies" to the "Pain Points" list
- Add the /r/reactjs subreddit and the Reactiflux Discord somewhere in the resources sections?

**Comment by SachaG** [comment]
@markerikson Great ideas!

> Might be nice to add a "just React state" option to the "State Management" section

Maybe, although we also have `useState` in the features section, and I also wonder if there are any React devs who *don't* use `useState`?

> Wish there was some way to differentiate between legacy "hand-written" Redux and modern Redux Toolkit

I can't think of a good way to do that, it's kind of like the Angular vs Angular.js problem… For that, the solution was to specify that we were asking about Angular and **not** about Angular.js with an explicit mention. I don't know if that works for Redux though? (I assume a lot of people still use Redux outside of Redux Toolkit). 

> Add some form of "Effects" or "Dependencies" to the "Pain Points" list

Would that be different from "Managing component re-renders"?

**Comment by phryneas** [comment]
>  I can't think of a good way to do that, it's kind of like the Angular vs Angular.js problem… For that, the solution was to specify that we were asking about Angular and not about Angular.js with an explicit mention. I don't know if that works for Redux though? (I assume a lot of people still use Redux outside of Redux Toolkit).

Generally, I would hope you list both - the user experience is fundamentally different between them, and a lot of the "not happy" users are bound to be legacy Redux users, not Redux Toolkit users.  
Conflating these two brings the "Redux" rating down every year and fuels a "people hate Redux" narrative that boils down to "people have not revisited the docs for 4 years and are rightfully angry that an outdated style of their library requires them to write a lot of code".

Having both in there might actually help people learn about Redux Toolkit and make the jump.

We are recommending Redux Toolkit as the default way of writing Redux since 2019. This survey should not get anyone reading the results to accidentally start using legacy Redux.

If you cannot list both, please ask about Redux Toolkit, not legacy Redux.  (Although both of them individually still have - by far - more users than any non-Redux option on the list, so I really think you can justify listing both.)

**Comment by phryneas** [comment]
Other things I noticed:

* I think you can stop listing redux-form. If you visit the homepage, you will see a deprecation note. The library is [deprecated since 2019](https://github.com/redux-form/redux-form/commit/220134950b9a383554021838f6fdbf74082f6828).
* `meta_frameworks` could also contain [RedwoodJs](https://redwoodjs.com/)
* I wouldn't add `joi`, `zod` or `yup` as "form tools" - that doesn't do them justice, they are used far beyond that. Might make sense as it's own category?
* `animation` could also contain [`react-native-reanimated`](https://docs.swmansion.com/react-native-reanimated/)
* `hosting` could also contain `generic docker` or `bare metal` - that would certainly be interesting to see
* maybe add [React Native Radio](https://reactnativeradio.com/) to the podcasts?

Suggestions:
A "which type of non-browser rendering" question: 
* custom SSG/SSR implementation built on renderToString
* SSG with a framework/library
* classic (non-streaming) SSR with a framework/library
* streaming SSR
* React Server Components

**Comment by SachaG** [comment]
> Generally, I would hope you list both - the user experience is fundamentally different between them, and a lot of the "not happy" users are bound to be legacy Redux users, not Redux Toolkit users.

My response to this argument regarding Angular has always been "if they're so different, then they should have different names" and I kinda feel the same about Redux vs Redux Toolkit…

All things considered I do think it's more interesting to ask about Redux Toolkit then "plain" Redux though so I'll either add both, or more likely add Redux Toolkit with a note to clarify.

**Comment by phryneas** [comment]
> "if they're so different, then they should have different names"

They have different names?

**Comment by filiptammergard** [comment]
I saw shadcn/ui was listed as a ui library, such it explicitly [states in its documentation](https://ui.shadcn.com/docs) that it's not. You cannot install shadcn/ui. It's rather a collection of copy-pastable components.

**Comment by filiptammergard** [comment]
I'd also say Tailwind CSS is not a ui library. Tailwind UI is one, but Tailwind CSS is just a CSS framework.

**Comment by SachaG** [comment]
@phryneas I suspect that the names are similar enough that non-Redux users are not aware of the difference.

**Comment by SachaG** [comment]
@filiptammergard thanks for the added details! But I'm not sure where else to include these two, so I don't think the distinction between UI libraries, CSS frameworks, etc. matters that much since there's so much overlap between the role they all play anyway.

**Comment by filiptammergard** [comment]
Tailwind CSS should go under "CSS Tools", since it's comparable with UNO CSS, Stitches etc and not comparable with component libraries like Radix.

**Comment by SachaG** [comment]
I get the point, I just don't think it would be useful to exclude the biggest player in this space from the category just to stick to an arbitrary classification. 

Tailwind UI being a paid product (if I'm not mistaken) I think its user numbers are going to be vastly inferior to Tailwind, so we might as well feature the larger of the two imo.

**Comment by SachaG** [comment]
It's tough, because on one hand we do want to capture as much useful data as possible, but on the other hand we don't usually differentiate between versions of the same library, no matter how big the improvements between versions. 

I'm just afraid that if we start down that path, other projects could argue just as strongly that Foo.js v2 is so much better than Foo.js v1 that it's only fair to split them out, to avoid bad Foo.js v1 opinions dragging down the overall rating for the library. 

Again I'm not against making exceptions to the rule if that gives us more useful data at the end of the day, but I just wanted to explain the reasoning behind my reticence.

**Comment by phryneas** [comment]
@SachaG, I get the reasoning behind the reticence - at the same time I have to admit that whole thing hurts a bit.  
As maintainers, we have been looking at these surveys for a few years now, and unfortunately, they don't give us (or anyone else) any useful data points, because they mix things together that don't belong together.

If you compared "legacy Redux" with "Redux Toolkit", it would be like comparing `redux` with `easy-peasy`, `kea` or `rematch`. Or like comparing `mobx` with `mobx-state-tree`. Or React itself with Next.js, Remix, Gatsby or Redwood.js.

Redux Toolkit is an opinionated framework for Redux.  
And much like the React team, we made the decision to say "don't use it plainly, use it with a framework" - only already four years ago, and we also published that officially recommended framework ourselves, based on what we had seen crystallize as best practices over the years. 

We had problems communicating that, and people kept hanging on to horrible outdated tutorials that were still teaching plain Redux, while they could only be writing 1/4 of the code (with safety wheels, much more typesafe, and without adding 25 other 3rd party packages for middleware etc.), so over the time we started referring to them as "legacy Redux" and "modern Redux", because that narrative seemed to work better to get people to actually switch over.

So maybe, based on that narrative, we somehow got you to the conclusion that RTK is just "redux 2.0", but in reality RTK bundles recommended middleware (and ships with new ones), streamlines project setup, ships new apis etc.
Meanwhile, the `redux` package itself published Version 5.0 beta two weeks ago. It's not like that is an "old thing" that will never get any update - we just don't want people to use it without a framework anymore.  
But some do, for various reasons, and they have a significantly different experience doing so.

Honestly, having these two different libraries as two data points would maybe even help convince people to finally make the jump from their legacy code to RTK.

But yeah, if all that doesn't convince you to add both of them, the main sentiment still stands: we want people to use the framework, and it is different enough to not be thrown into one pot with the `redux` package. Please only mention RTK in the survey then, not "Redux" as a blanket statement.

**Comment by SachaG** [comment]
> As maintainers, we have been looking at these surveys for a few years now, and unfortunately, they don't give us (or anyone else) any useful data points, because they mix things together that don't belong together.

Just to clarify, we've never done a State of React survey before. And if you mean the State of JS surveys, unless I'm mistaken I think the last time Redux was featured as a survey item was in 2020.

**Comment by phryneas** [comment]
@SachaG Honestly, I'm not sure which survey it was, it could also have been in a "competing" survey - but we have seen this "Redux" all-in-one-bucket again and again - and tbh., that's very frustrating, because it fires a narrative that just doesn't reflect any reality. I'm extremely happy that for once we have the ability to give feedback to a survey design here before the survey happens :)

**Comment by slorber** [comment]
Are we supposed to open PRs at this point or only provide text feedback?

Does it also cover React-Native? If so how much? 
Note: there's a [State of React-Native survey](https://results.stateofreactnative.com/) already.

What I would like to have is a list of "React Renderers & Platforms" people have used:
- Web
- React-Three-Fiber
- Remotion
- React-Ink
- MJML-React / React-Email
- React-Native-Web (although it's an edge case it's cool to include it)
- React-Native iOS
- React-Native Android
- React-Native macOS
- React-Native Windows
- React-Native-Skia

Some quick feedback:
- Hooks: missing hook `useInsertionEffect` (although it might be on purpose due to very niche usecase)
- Would also separate Redux from Redux Toolkit
- Would also like having "Just React" as state management
- Would also like a schema/validation library category (joi,yup,zod,ts-io...)
- Would also like a network wiring category: (RSC, tRPC, Blitz...)
- `Data Loading` could be eventually be renamed as `Async State Management`? Solutions usually can handle Async browser APIs too (could be qualified as "loading"? 🤷‍♂️ )
- Other popular data loading solutions: [suspend-react](https://www.npmjs.com/package/suspend-react), [react-async-hook)[https://www.npmjs.com/package/react-async-hook]
- UI libraries: would be nice to feature things like React-Aria, Ariakit, Reach-ui... IMHO that's a bit similar to Headless UI.
- Frameworks: would add Redwood
- Mobile: add Capacitor? (often used with Ionic bot afaik not only)
- Build tools: turbopack, rspack? (not mainstream yet but could be useful have awareness of those)
- Backend languages: Scala, Elixir, Haskell? could be useful to see how much FP the React community is.
- Data visualization: D3, Tremor?
- CSS Tools & libs: would put Tailwind there instead of UI libs
- Other Services: Axiom, Neon, PostHog, Datadog, Segment?
- React Pain Points: debugging, performance? remove legacy synthetic events?
- Blogs & Magazines: what is React Weekly? 😅 Maybe you meant [This Week In React](http://thisweekinreact.com/) 😜 
- Podcasts: JavaScript Jam, React-Native-Radio, The React-Native Show?
- Video creators: Sam Selikoff, Jason Lengstorf, Web Dev Cody, Ben Holmes, William Candillon, notJust.dev? Some in your list do not look super related to React.
- People: some do not feel like part of the React ecosystem? 🤔 . Also hope I could be added there 😇
- Surveys: State of React-Native?

In case it's useful: list of active and qualitative (non-automated list of SEO articles newsletters for React developers:
- 50k subs: https://react.statuscode.com/
- 22k subs: http://thisweekinreact.com/
- 18k subs: https://reactdigest.net/
- 3k subs: https://nextjsweekly.com/

**Comment by SachaG** [comment]
Thanks for the feedback!

- added Redwood
- split validation tools into their own category
- removed Redux Form
- added React Native Reanimated
- added Azure in hosting category
- added React Native Radio
- split out Redux/Redux Toolkit
- added State of React Native survey
- added `useState` to State Management section
- added io-ts
- added React Aria, Ariakit, Reach UI
- added Capacitor
- added turbopack
- added Scala, Elixir, Haskell
- added D3, tremor
- react_weekly => this_week_in_react, whoops!
- added JavaScript Jam, React-Native-Radio, The React-Native Show
- added Sam Selikoff, Jason Lengstorf, Web Dev Cody, Ben Holmes, William Candillon, notJust.dev

**Comment by SachaG** [comment]
Other points:

> Suggestions: A "which type of non-browser rendering" question:
> 
> * custom SSG/SSR implementation built on renderToString
> * SSG with a framework/library
> * classic (non-streaming) SSR with a framework/library
> * streaming SSR
> * React Server Components

That seems a bit too in-depth/tricky to explain the nuances during the survey. I'm not against asking about streaming though, maybe as part of the "other features" section?

> Are we supposed to open PRs at this point or only provide text feedback?

Text feedback is fine. 

> Does it also cover React-Native? If so how much?

Probably not too much given that there's already a survey for that. 

> What I would like to have is a list of "React Renderers & Platforms" people have used:

I'm not sure how many people actually use all of these apart from React Native? Maybe too niche to mention? Or else have a grab-bag "other tools" category?

> Hooks: missing hook useInsertionEffect (although it might be on purpose due to very niche usecase)

Yes it seemed a bit too niche. 

> Would also like a network wiring category: (RSC, tRPC, Blitz...)

RSCs and tRPC are already in the survey, but not sure where to fit Blitz… maybe in the meta-frameworks category, even though it sits on top of another meta-framework?

**Comment by SachaG** [comment]
Also updated the People list, and added a new question about AI Tools.

**Comment by slorber** [comment]
> > What I would like to have is a list of "React Renderers & Platforms" people have used:
> 
> I'm not sure how many people actually use all of these apart from React Native? Maybe too niche to mention? Or else have a grab-bag "other tools" category?

Some of those renderers are quite widely used. In any case even if usage is low I think a dedicated survey tab would be great for renderers and give the ability to bring awareness to the cross-platform abilities of React. Today many still don't know it's possible to create Desktop apps in React, or videos for example.

Here's my estimation of usage per renderer:
- Web ⭐️⭐️⭐️⭐️⭐️
- React-Three-Fiber ⭐️⭐️⭐️
- Remotion ⭐️⭐️
- React-Ink ⭐️⭐️
- React-pdf ⭐️⭐️⭐️
- MJML-React / React-Email ⭐️⭐️
- React-Native-Web ⭐️⭐️⭐️
- React-Native iOS ⭐️⭐️⭐️⭐️
- React-Native Android ⭐️⭐️⭐️⭐️
- React-Native macOS ⭐️
- React-Native Windows ⭐️
- React-Native-Skia ⭐️⭐️⭐️

Eventually, we can group techs by "target":
- Web
- Mobile
- Desktop
- Emails
- TV
- CLI
- Documents (pdf, docs, slideshows...)
- Video
- 3D / VR

> > Would also like a network wiring category: (RSC, tRPC, Blitz...)
> 
> RSCs and tRPC are already in the survey, but not sure where to fit Blitz… maybe in the meta-frameworks category, even though it sits on top of another meta-framework?

I don't know 😅

**Comment by SachaG** [comment]
OK, I added the Renderers question. At this point I think the survey is looking fairly complete, and we should probably start thinking about things to cut down rather than things to add, especially from the "Other Tools" section which is looking quite full… Who knew the React ecosystem was so large!

**Comment by filiptammergard** [comment]
I still really think Tailwind should be moved from UI libraries to CSS tools. When people talk about Tailwind it's almost always the CSS tool (comparable to the ones in the CSS tools section) and not the Tailwind UI component library.

People will definitely find it strange not being able to choose Tailwind in CSS tools section when they can choose UnoCSS, Vanilla Extract etc.

**Comment by SachaG** [comment]
OK I'll make that change too.

**Comment by SachaG** [comment]
Btw, I wonder if we could find more questions to identify how the community feels about the current shift towards Next.js/RSCs/meta-frameworks/etc. as discussed in this thread and on Twitter. 

To me it seems like there's two distinct axes that people disagree on, the "amount of work" axis and the "amount of value" axis. The React team would probably argue that RSCs don't require a ton of work to add to your app and bring a lot of value, while the negative case would be that they do require a lot of work for not that much in return. Maybe we could find a way to phrase questions around that concept?

**Comment by slorber** [comment]
Wonder how useful collecting the sentiment of the community on this topic would be. It's probably a bit too new and people haven't actually used RCSs in production for real world websites.

---

Unrelated but was wondering if this button for long lists wouldn't bias the survey toward the first list items.

<img width="173" alt="CleanShot 2023-06-19 at 19 52 52@2x" src="https://github.com/Devographics/surveys/assets/749374/3cc7b3b6-0ec8-478f-953e-429e2190550a">

I don't really have a better solution with decent UX 😅 Maybe the "sample" before that button is pressed could be made more visible, or the sample could be randomized?

**Comment by SachaG** [comment]
> Unrelated but was wondering if this button for long lists wouldn't bias the survey toward the first list items.

Yes, it's a risk. For lists featuring more subjective items (pain points, etc.) the items are randomized. For things like e.g. Podcasts I assume that you either listen or don't listen to a podcast, so I just order them alphabetically and hope it won't impact the data too much.

**Comment by charkour** [comment]
As of Node v18 and v16.17.0, there is a test runner built into Node. Is it too niche to add to the testing tools? https://nodejs.org/docs/latest-v20.x/api/test.html

**Comment by charkour** [comment]
Also, I know bootstrap CSS has fallen out of favor but it's still widely used. I know you've taken it out of past surveys, but I wanted to throw out the idea. Thanks!

**Comment by SachaG** [comment]
Thanks for the suggestions! I believe we do have react-bootstrap as one of the options.

**Comment by leerob** [comment]
For Other APIs
- Server Actions https://react.dev/reference/react/use-server

For State Management
- Should things like URL state or server state be included? E.g. what Remix encourages

Data Loading
- I would add Server Components: https://github.com/acdlite/rfcs/blob/first-class-promises/text/0000-first-class-support-for-promises.md
- Remix Loaders

Metaframeworks
- Hydrogen

AI Tools
- Vercel AI SDK https://sdk.vercel.ai/docs

For Pain Points
- I'd recommend breaking apart "Server-Side Rendering & Server Components"
- Would help to be more granular here, maybe
  - Implementing server-side rendering
  - Learning Server Components
  
New Features
- Server Actions maybe (experimental)?

**Comment by SachaG** [comment]
Since it's been a while since I last worked on the survey I decided to revisit it and simplify it a bit, in the hopes of launching it imminently. Here's the updated version: https://survey.devographics.com/en-US/survey/state-of-react/2023

**Comment by filiptammergard** [comment]
I think it looks really good! 👍

**Comment by webdevUXR** [comment]
Hey Sacha, I suggested this for State of HTML, but we could benefit from additional pain points items in the "about you" section. This will help us check reliability of estimates across other surveys shared with W3C WebDX CG and allow us to tie generic pain points to JS-specific pain points identified in other sections of this survey. The question is a simple matrix -- or it could be five standalone single-choice items. 

Matrix version: 

"Here are some general tasks you may do as part of your work in web development. How painful or not painful is each task to you?
(Answer cat: Extremely painful, Very painful, Somewhat painful, Not very painful, Not at all painful)

- investigating and triaging a bug
- Keeping up with large number of tools/frameworks
- Making a design work the same across browsers
- Dealing with negative effects of browser updates
- Dealing with deprecations/removals of language features/web APIs
- Keeping up with new features in web standards

Individual items: 

As part of your work in web development, how painful or not painful is {item 1}
As part of your work in web development, how painful or not painful is {item 2}
etc.

Thanks for considering!
